- name: create data directory
  file:
    path: /var/lib/redis
    state: directory
    recurse: true

- name: start redis
  docker_container:
    name: redis
    image: docker.mirrors.ustc.edu.cn/library/redis:6.2.4
    state: started
    recreate: true
    restart_policy: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "/var/lib/redis:/data"
    command: redis-server --appendonly yes
