- name: create data directory
  file:
    path: /var/lib/redis
    state: directory

- name: start redis
  shell: >-
    docker run -d
    --name redis
    --restart always
    --network host
    --log-opt max-file=10
    --log-opt max-size=100m
    -v /var/lib/redis:/data
    docker.io/library/redis:6.2.4
    redis-server --appendonly yes
