- name: start container
  docker_container:
    name: socks5x
    image: wizawu/brook:latest
    state: started
    recreate: true
    restart_policy: always
    network_mode: host
    entrypoint: /usr/local/bin/npm
    command: run start
    working_dir: /opt/app
    volumes:
      - "{{role_path}}/files:/opt/app"
