- name: start container
  docker_container:
    name: socks5x
    image: wizawu/brook:latest
    state: started
    recreate: true
    restart_policy: always
    network_mode: host
    dns_servers:
      - 223.5.5.5
      - 223.6.6.6
      - 8.8.8.8
      - 8.8.4.4
    entrypoint: /usr/local/bin/npm
    command: run start
    working_dir: /opt/app
    volumes:
      - "{{role_path}}/files:/opt/app"
