- name: start container
  shell: >-
    podman run
    -d --replace
    --name socks
    --restart always
    --network host
    --dns 223.5.5.5
    --dns 223.6.6.6
    --dns 8.8.8.8
    --dns 8.8.4.4
    --log-driver json-file
    --log-opt max-file=10
    --log-opt max-size=100m
    -v {{role_path}}/files:/opt/proxy
    -w /opt/proxy
    --entrypoint /usr/local/bin/npm
    wizawu/proxy:latest
    run start
