- hosts: localhost
  become: true

  tasks:
    - name: reconfigure tzdata
      cron:
        name: reconfigure tzdata
        special_time: reboot
        job: dpkg-reconfigure -f noninteractive tzdata

    - name: updatedb
      cron:
        name: updatedb
        special_time: daily
        job: updatedb

    - name: update vscode
      cron:
        name: update vscode
        special_time: daily
        job: apt update -y && apt install -y code
