- hosts: localhost
  become: true

  tasks:
    - name: reconfigure tzdata
      cron:
        name: reconfigure tzdata
        special_time: reboot
        job: dpkg-reconfigure -f noninteractive tzdata

    - name: updatedb
      cron:
        name: updatedb
        special_time: daily
        job: updatedb
