- hosts: localhost
  become: true

  tasks:
    - name: reconfigure tzdata
      cron:
        name: reconfigure tzdata
        special_time: reboot
        job: dpkg-reconfigure -f noninteractive tzdata

    - name: updatedb
      cron:
        name: updatedb
        special_time: daily
        job: updatedb

    - name: save github starred
      cron:
        name: save github starred
        special_time: hourly
        job: >-
          bash -c "curl -sk -m 60 --socks5 127.0.0.1:1080
          'https://api.github.com/users/wizawu/starred?per_page=99' | jq -r
          '.[].svn_url' > /home/wizawu/github/starred/\$(date +\%F).json"
