- hosts: localhost
  vars_prompt:
    - name: agree
      prompt: Cancel the play with CTRL+C or continue with ENTER

  tasks:
    - name: create user
      user: name={{user}} state=present group=root shell=/bin/bash

    - name: change file mode of this repo
      file:
        dest: /home/{{user}}/.sysconf
        state: directory
        recurse: true
        owner: "{{user}}"

    - name: locale-gen
      locale_gen: name={{item}} state=present
      with_items:
        - en_US.UTF-8
        - zh_CN
        - zh_CN.GB18030
        - zh_CN.GBK
        - zh_CN.UTF-8

    - name: create symbolic link to apt sources.list
      file:
        src: /home/{{user}}/.sysconf/etc/apt/sources.list.d
        dest: /etc/apt/sources.list.d
        state: link
        force: true

    - name: add apt keys
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv {{item}}
      with_items:
        - 1655A0AB68576280 # node
        - 3B4FE6ACC0B21F32 # tsinghua
        - 6A030B21BA07F4FB # aliyun kubernetes
        - 7EA0A9C3F273FCD8 # aliyun docker

    - name: install apt packages
      apt:
        update_cache: true
        install_recommends: false
        name:
          - acpi
          - alsa-oss
          - alsa-tools
          - alsa-utils
          - apache2-utils
          - bash-completion
          - cifs-utils
          - colortail
          - debootstrap
          - dnsutils
          - docker-ce
          - docker-compose
          - dstat
          - entr
          - expect
          - f2fs-tools
          - fio
          - fiu-utils
          - g++
          - gcp
          - glusterfs-client=5.5-3
          - grub2-common
          - haproxy
          - hdparm
          - hsetroot
          - im-config
          - lftp
          - lm-sensors
          - locate
          - lshw
          - lsof
          - m4
          - make
          - manpages-dev
          - netcat
          - nethogs
          - nfs-common
          - nginx
          - nmap
          - nodejs
          - ntfs-3g
          - p7zip-full
          - parallel
          - pppoeconf
          - psmisc
          - pulseaudio
          - putty-tools
          - python3-pip
          - python3-setuptools
          - rcconf
          - rinetd
          - rlwrap
          - rsync
          - smbclient
          - sntp
          - software-properties-common
          - ssh
          - sshfs
          - sshpass
          - strace
          - supervisor
          - sysbench
          - syslog-ng
          - sysstat
          - systemd-sysv
          - tlp
          - tlp-rdw
          - wpasupplicant

    - name: check built-in tools
      shell: command -v {{item}}
      with_items:
        - getconf
        - ipcs
        - losetup
        - lscpu
        - lsusb
        - pmap
        - trap

    - name: install database packages
      apt:
        name:
          - mydumper
          - mysql-client
          - postgresql-client
          - redis-tools
          - sqlite3

    - include: tasks/command.yml
    - include: tasks/desktop.yml
    - include: tasks/vscode.yml
    - include: tasks/pip.yml
    - include: tasks/npm.yml
    - include: tasks/uninstall.yml

    - name: create etc directories
      file: dest=/{{item}} state=directory recurse=yes
      with_items:
        - etc/X11/xorg.conf.d
        - etc/apt/apt.conf.d
        - etc/fonts/conf.d
        - etc/opt/chrome/policies/managed
        - etc/security/limits.d
        - etc/supervisor/conf.d
        - etc/xdg/awesome

    - name: create symbolic link to global config
      file: src=/home/{{user}}/.sysconf/{{item}} dest=/{{item}} state=link force=yes
      with_items:
        - etc/X11/xorg.conf.d/99-synaptics.conf
        - etc/apt/apt.conf.d/99default
        - etc/fonts/conf.d/99-default.conf
        - etc/opt/chrome/policies/managed/blocklist.json
        - etc/rc.local
        - etc/xdg/awesome/rc.lua

    - name: create template config
      template: src={{item}}.tpl dest=/{{item}} mode=0440
      with_items:
        - etc/security/limits.d/default.conf
        - etc/sudoers.d/default

    - name: remove font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        regexp: '^\s{0,}<dir'
        state: absent

    - name: add font dir
      lineinfile:
        dest: /etc/fonts/fonts.conf
        line: "\t{{item}}"
        insertafter: "<fontconfig"
      with_items:
        - "<dir>~/.fonts</dir>"

    - name: update tsocks config
      lineinfile:
        dest: /etc/tsocks.conf
        regexp: '^server\s{0,}='
        line: "server = 127.0.0.1"

    - name: disable NetworkManager dns
      lineinfile:
        dest: /etc/NetworkManager/NetworkManager.conf
        regexp: '^dns\s{0,}='
        line: "dns=none"
        insertafter: "[main]"
      ignore_errors: true

    - name: restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      ignore_errors: true

    - name: disable splash screen
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT\s{0,}='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT=""'

    - name: update grub config
      command: update-grub2

    - name: update systemd logind.conf
      lineinfile:
        dest: /etc/systemd/logind.conf
        regexp: '^{{item.key}}\s{0,}='
        line: "{{item.key}}={{item.value}}"
      with_items:
        - { key: "HandleLidSwitch", value: "ignore" }
        - { key: "HandlePowerKey", value: "suspend" }

    - name: disable grp:alt_shift_toggle
      shell: sed -i -e 's/grp:alt_shift_toggle,\?//g' /etc/default/keyboard

    - name: configure kernel parameters
      sysctl:
        name: "{{item.name}}"
        value: "{{item.value}}"
      with_items:
        - name: fs.inotify.max_user_watches
          value: 524288
        - name: kernel.pid_max
          value: 999999

    - name: create user directories
      file: dest=/home/{{user}}/{{item}} state=directory recurse=yes owner={{user}}
      with_items:
        - .gradle
        - .ssh

    - name: create symbolic link to user config
      file:
        src: /home/{{user}}/.sysconf/dotfiles/{{item}}
        dest: /home/{{user}}/.{{item}}
        state: link
        force: true
        owner: "{{user}}"
      with_items:
        - bashrc
        - gitconfig
        - gradle/gradle.properties
        - sqliterc
        - ssh/config
        - tmux.conf
        - vimrc
        - xinitrc

    - name: copy modified background
      copy:
        src: dotfiles/config/background.png
        dest: /usr/share/awesome/themes/default/background.png
        remote_src: true
