- name: disable services
  service:
    name: "{{item}}"
    state: stopped
    enabled: false
  ignore_errors: true
  with_items:
    - snapd
    - snapd.seeded
    - snapd.socket
    - systemd-resolved

- name: uninstall packages
  apt:
    state: absent
    name:
      - cloud-init
      - pcp
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr

- name: clean apt cache
  apt:
    autoremove: true
    purge: true
    clean: true

- name: disable execution
  file:
    path: /usr/bin/{{item}}
    mode: 400
  ignore_errors: true
  with_items:
    - cinnamon-screensaver
    - csd-clipboard
    - csd-keyboard
    - csd-media-keys
    - csd-screensaver-proxy
    - nemo-desktop

- name: remove qt5ct config
  file:
    path: /etc/X11/Xsession.d/99qt5ct
    state: absent
