- name: install cli tools
  apt:
    name:
      - ack-grep
      - apt-file
      - autossh
      - cmake
      - cmatrix
      - cpulimit
      - curl
      - dconf-cli
      - di
      - fish
      - fonttools=3.0-1
      - fping
      - git-extras
      - gnupg1
      - htop
      - httrack
      - iftop
      - inotify-tools
      - iotop
      - jq
      - less
      - linux-cpupower
      - mtr
      - nethogs
      - pv
      - rar
      - time
      - tmux
      - tree
      - tsocks
      - unrar
      - unzip
      - upower
      - valgrind
      - whois
      - wput
      - yamllint

- name: remove useless git commands
  file:
    src: /usr/bin/{{item}}
    state: absent
  with_items:
    - git-alias
    - git-archive-file
    - git-authors
    - git-commits-since

- name: download antlr4
  get_url:
    url: https://www.antlr.org/download/antlr-4.9.3-complete.jar
    dest: /usr/share/java/antlr-complete.jar
