- name: install desktop
  apt:
    name:
      - awesome
      - awesome-extra
      - code
      - cpupower-gui
      - dbus-x11
      - diffuse
      - geany # text editor
      - gimp
      - mirage # image viewer
      - mupdf
      - pavucontrol
      - picom # fix chrome menu border
      - redshift
      - smplayer
      - tilix
      - vim-gtk
      - wireshark-gtk
      - x11-xkb-utils
      - x11-xserver-utils
      - xdg-desktop-portal
      - xdg-user-dirs
      - xinput
      - xorg
      - xsel
      - xserver-xorg-input-all
      - xserver-xorg-input-kbd
      - xserver-xorg-input-synaptics
      - xtrlock

- name: uninstall packages
  apt:
    state: absent
    name:
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr

- name: install input method
  apt:
    name:
      - fcitx-config-gtk
      - fcitx-frontend-gtk3
      - fcitx-googlepinyin
      - fcitx-module-x11

- name: install fcitx skin
  shell: >-
    wget https://codeload.github.com/{{item}}/tar.gz/refs/heads/master -qO- |
    tar zxf - --strip-component=1 -C /usr/share/fcitx/skin/
  with_items:
    - 22dm/fcitx-solarized-skin
    - Yucklys/fcitx-nord-skin

- name: install packages from url
  apt: deb={{item}}
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - https://github.com/flameshot-org/flameshot/releases/download/v12.1.0/flameshot-12.1.0-1.debian-10.amd64.deb

- name: install cinnamon
  apt:
    install_recommends: true
    name:
      - cinnamon-session
      - cinnamon-settings
      - nautilus
      - network-manager-gnome

- name: disable deepin-devicemanager-server
  service: name=deepin-devicemanager-server state=stopped enabled=false

- name: remove nemo-desktop
  shell: mv /usr/bin/nemo-desktop /usr/bin/.nemo-desktop
