- name: install desktop
  apt:
    name:
      - autorandr
      - awesome
      - awesome-extra
      - code
      - dbus-x11
      - geany # text editor
      - gimp
      - mirage # image viewer
      - pavucontrol
      - qpdfview
      - redshift
      - smplayer
      - tilix
      - vim-gtk
      - wireshark-gtk
      - x11-xkb-utils
      - x11-xserver-utils
      - xdg-user-dirs
      - xinput
      - xorg
      - xsel
      - xserver-xorg-input-all
      - xserver-xorg-input-kbd
      - xserver-xorg-input-synaptics
      - xtrlock

- name: install input method
  apt:
    name:
      - fcitx
      - fcitx-config-gtk
      - fcitx-frontend-gtk3
      - fcitx-googlepinyin
      - fcitx-modules
      - fcitx-ui-classic
      - fcitx-ui-light
      - libgtk-3-bin

- name: install packages from url
  apt: deb={{item}}
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - https://github.com/flameshot-org/flameshot/releases/download/v12.1.0/flameshot-12.1.0-1.debian-10.amd64.deb

- name: install cinnamon
  apt:
    install_recommends: true
    name:
      - cinnamon-session
      - cinnamon-settings
      - nautilus
      - network-manager-gnome

- name: disable deepin-devicemanager-server
  service: name=deepin-devicemanager-server state=stopped enabled=false

- name: remove nemo-desktop
  shell: mv /usr/bin/nemo-desktop /usr/bin/.nemo-desktop
