- name: install desktop
  apt:
    name:
      - autorandr
      - awesome
      - awesome-extra
      - code
      - cups # printer
      - dbus-x11
      - deepin-screenshot=4.1.8-1
      - deepin-wine5-i386
      - dolphin
      - draw.io
      - freerdp-x11
      - geany # text editor
      - gimp
      - gthumb # image viewer
      - gtk-theme-switch
      - kde-config-gtk-style
      - kde-config-screenlocker
      - pavucontrol
      - plasma-desktop
      - plasma-nm
      - qbittorrent
      - qpdfview
      - redshift
      - smplayer
      - systemsettings # KDE settings center
      - tilix
      - vim-gtk
      - wireshark-gtk
      - wps-office
      - x11-xkb-utils
      - x11-xserver-utils
      - xdg-user-dirs
      - xinput
      - xorg
      - xsel
      - xserver-xorg-input-all
      - xserver-xorg-input-kbd
      - xserver-xorg-input-synaptics
      - xtrlock

- name: install input method
  apt:
    name:
      - fcitx
      - fcitx-config-gtk
      - fcitx-frontend-gtk3
      - fcitx-googlepinyin
      - fcitx-modules
      - fcitx-ui-classic
      - fcitx-ui-light
      - libgtk-3-bin

- name: install sogou pinyin
  apt:
    deb: https://ime.sogouimecdn.com/202203030042/60dab1bb3843ee20ea272f288c2aeb80/dl/index/1639750479/sogoupinyin_3.4.0.9700_amd64.deb

- name: install chrome
  apt: deb=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: download waterfox
  shell: >-
    wget https://cdn.waterfox.net/releases/linux64/installer/waterfox-G4.0.2.en-US.linux-x86_64.tar.bz2
    -qO - | tar -xjf - -C /home/{{user}}/local/
