- name: install npm packages
  shell: "npm install -g {{item}}"
  with_items:
    - base-x-bin@1.0.x
    - fmt2i@latest
    - http-proxy-to-socks@1.1.x
    - otplib@12.x.x
    - prettier@2.4.1
    - typescript@latest
