- name: set pip index url
  shell: pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

- name: install python packages
  pip:
    name:
      - ansible-lint==5.0.7
      - ansible==2.9.9
      - black==20.8b1
      - docker==4.2.1
      - isort==5.7.0
      - mycli==1.24.1
      - wheel==0.36.2
      - yq==2.13.0
    executable: pip3
