version: "3.3"
services:
  samba:
    container_name: samba
    image: xxxx.mirror.aliyuncs.com/dperson/samba:latest
    restart: "no"
    ports:
      - 139:139
      - 445:445
    volumes:
      - "/home/wizawu/local/share:/share"
    command: -s "public;/share;yes;no;yes"
