- name: create data directory
  file:
    path: "/home/wizawu/local/share"
    state: directory
    recurse: true
    mode: 0777

- name: start samba
  shell: |
    docker-compose pull
    docker-compose up -d --force-recreate
  args:
    chdir: "{{role_path}}/files"
