- name: start phpmyadmin
  shell: >-
    podman run
    -d --replace
    -p 3309:80
    -e PMA_ARBITRARY=1
    --name phpmyadmin
    --restart always
    --log-opt max-file=10
    --log-opt max-size=100m
    phpmyadmin/phpmyadmin:5.2.0
