- name: create data directory
  file:
    path: /var/lib/mysql
    state: directory

- name: start mysql
  shell: >-
    podman run
    -d --replace
    --name mysql
    --restart always
    --network host
    --log-opt max-file=10
    --log-opt max-size=100m
    -v /var/lib/mysql:/var/lib/mysql
    -v {{playbook_dir}}/roles/mysql/files/conf.d:/etc/mysql/conf.d
    -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
    docker.mirrors.ustc.edu.cn/library/mysql:8.0.22
