- set_fact:
    ss: "{{lookup('file', '/etc/shadowsocks/config.json') | from_json}}"

- name: start brook
  shell: >-
    docker run -d
    --name brook
    --restart always
    --network host
    --dns 1.2.4.8
    --dns 8.8.4.4
    --dns 8.8.8.8
    --log-opt max-file=10
    --log-opt max-size=100m
    --entrypoint /bin/sh
    docker.io/wizawu/proxy:latest
    -c "brook socks5 -i 127.0.0.1 -l 127.0.0.1:1080
    & brook ssclient -i 127.0.0.1 -l 127.0.0.1:1081
    -p {{ss.password}} -s {{ss.server}}:{{ss.server_port}}"
