- name: get password
  shell: jq .password /home/wizawu/github/vpsconf/templates/shadowsocks.json
  register: password

- name: start brook
  docker_container:
    name: brook
    image: wizawu/proxy:latest
    state: started
    recreate: true
    restart_policy: always
    network_mode: host
    dns_servers:
      - 223.5.5.5
      - 223.6.6.6
      - 8.8.8.8
      - 8.8.4.4
    entrypoint: /bin/sh
    command: >-
      -c "brook socks5 -i 127.0.0.1 -l 127.0.0.1:1080
      & brook ssclient -i 127.0.0.1 -l 127.0.0.1:1081
      -p {{password.stdout}} -s shadowsocks.local:3308"
    log_driver: json-file
    log_options:
      max-file: "10"
      max-size: "100m"
