- name: get server
  shell: jq .server /home/wizawu/github/vpsconf/templates/shadowsocks.json
  register: server

- name: get password
  shell: jq .password /home/wizawu/github/vpsconf/templates/shadowsocks.json
  register: password

- name: start brook
  docker_container:
    name: brook
    image: wizawu/brook:latest
    state: started
    recreate: true
    restart_policy: always
    network_mode: host
    dns_servers:
      - 223.5.5.5
      - 8.8.8.8
    entrypoint: /bin/sh
    command: >-
      -c "sockd -D && brook ssclient -i 127.0.0.1 -l 127.0.0.1:1081
      -p {{password.stdout}} -s {{server.stdout}}:3308"
    volumes:
      - "{{role_path}}/files/sockd.conf:/etc/sockd.conf"
