- set_fact:
    ss: "{{lookup('file', '/etc/shadowsocks/config.json') | from_json}}"

- name: start brook
  shell: >-
    docker run -d
    --name brook
    --restart always
    --network host
    --dns 1.2.4.8
    --dns 8.8.4.4
    --dns 8.8.8.8
    --log-opt max-file=10
    --log-opt max-size=100m
    --entrypoint /bin/sh
    docker.io/geosmart/proxy:latest
    -c "brook --log console  client  --socks5 0.0.0.0:1080  -p {{ss.password}} -s {{ss.server}}:{{ss.port}}"
