name: build docker images
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login registry
        run: echo ${{secrets.DOCKER_HUB_PASSWORD}} | docker login -u geosmart --password-stdin

      - name: build proxy image
        run: cd docker/proxy && docker build . -t geosmart/proxy:latest

      - name: push proxy image
        run: docker push geosmart/proxy:latest